# Based on the Carbon Design System:
# https://carbondesignsystem.com/guidelines/color/usage

[wallpaper]
wallpaper = "~/.config/qtile/wallpaper/carbon.png"
wallpaper_mode = "fill"

[fonts]
default = "IBM Plex Sans"
symbols = "BlexMono Nerd Font"

[layouts]
[layouts.default]
grow_amount         = 3
margin              = 6
border_width        = 3
border_focus        = "#4589ff"
border_normal       = "#393939"
border_normal_stack = "#393939"
border_focus_stack  = "#be95ff"

[layouts.columns]
num_columns = 3

[layouts.floating]
border_width = 0

[widgets]
[widgets.default]
fontsize   = 16
padding    = 6
foreground = "#f4f4f4"
background = "#161616"

[widgets.icon]
fontsize   = 20
padding    = 6
foreground = "#f4f4f4"
background = "#161616"

[widgets.battery]
low_foreground = "#ff8389"

[widgets.clock]
foreground = "#78a9ff"

[widgets.launcher]
foreground = "#f1c21b"

[widgets.quickexit]
foreground = "#fa4d56"

[widgets.volume]
foreground = "#f4f4f4"

[widgets.notify]
foreground_low    = "#8d8d8d"
foreground_urgent = "#ff8389"

[widgets.current_layout_icon]
scale = 0.6

[widgets.groupbox]
foreground                  = "#f4f4f4"
active                      = "#c6c6c6"
inactive                    = "#6f6f6f"
highlight_method            = "line"
highlight_color             = "#393939"
this_current_screen_border  = "#4589ff"
this_screen_border          = "#6f6f6f"
other_current_screen_border = "#8d8d8d"
other_screen_border         = "#6f6f6f"
urgent_alert_method         = "line"
urgent_text                 = "#ff8389"

[widgets.current_screen]
active_color   = "#f4f4f4"
active_text    = "Α"
inactive_color = "#8d8d8d"
inactive_text  = "ι"
