[wallpaper]
wallpaper = "~/.config/qtile/wallpaper/catppuccin.png"
wallpaper_mode = "fill"

[fonts]
default = "Fira Sans"
symbols = "FiraCode Nerd Font"

[layouts]
[layouts.default]
margin        = 6
border_width  = 3
border_focus  = "#b4befe"
border_normal = "#6c7086" # Overlay0
grow_amount   = 3

[layouts.columns]
num_columns = 3

[layouts.floating]
border_width = 0

[widgets]
[widgets.default]
fontsize   = 16
padding    = 6
foreground = "#cdd6f4"
background = "#1e1e2e"

[widgets.icon]
fontsize   = 20
padding    = 6
foreground = "#cdd6f4"
background = "#1e1e2e"

[widgets.battery]
low_foreground  = "#eba0ac"

[widgets.calendar]
foreground = "#cba6f7"

[widgets.clock]
foreground = "#cba6f7"

[widgets.launcher]
foreground = "#f9e2af"

[widgets.quickexit]
foreground = "#f38ba8"

[widgets.volume]
foreground = "#94e2d5"

[widgets.current_layout_icon]
scale = 0.6

[widgets.groupbox]
pading                      = 8
foreground                  = "#cdd6f4"
borderwidth                 = 0
active                      = "#74c7ec"
inactive                    = "#7f849c"
highlight_method            = "line"
highlight_color             = "#45475a"
this_current_screen_border  = "#89b4fa"
this_screen_border          = "#cdd6f4"
other_current_screen_border = "#45475a"
other_screen_border         = "#45475a"
urgent_alert_method         = "text"
urgent_text                 = "#eba0ac"

[widgets.current_screen]
active_color   = "#a6e3a1"
active_text    = "Α"
inactive_color = "#eba0ac"
inactive_text  = "ι"
