# General tmux configuration when working for AIT-IS @ Wheaton College

session_name: ait

windows:
  - window_name: local
  - window_name: cslab
  - window_name: salt
  - window_name: olm
  - window_name: nagios
  - window_name: test
  - window_name: ssh