# Modified oxocarbon theme from
# https://github.com/nyoom-engineering/oxocarbon-alacritty

colors:
  primary:
    foreground: "#ffffff"
    background: "#161616"

  search:
    matches:
      foreground: CellBackground
      background: "#ee5396"
    footer_bar:
      foreground: "#262626"
      background: "#ffffff"

  selection:
    text:       "#161616"
    background: "#8d8d8d"

  normal:
    black:   "#262626"
    magenta: "#ff7eb6"
    green:   "#42be65"
    yellow:  "#ffe97b"
    blue:    "#33b1ff"
    red:     "#ee5396"
    cyan:    "#3ddbd9"
    white:   "#dde1e6"

  bright:
    black: "#393939"
    magenta: "#ff7eb6"
    green: "#42be65"
    yellow: "#ffe97b"
    blue: "#33b1ff"
    red: "#ee5396"
    cyan: "#3ddbd9"
    white: "#ffffff"
