#!/usr/bin/env sh
# File: .xprofile

~/.dwm/bar.sh &

gnome-keyring-daemon --start --components=secrets &
light-locker --lock-on-lid &
nm-applet --indicator &
gammastep-indicator &

if [ "${XDG_SESSION_TYPE}" = "x11" ] ; then
  picom -b &
elif [ "${XDG_SESSION_TYPE}" = "wayland" ] ; then
  :
fi

# vim: ft=sh
