"""Provides helpful variables for keyboard keys."""

ALT = "mod1"
HYPER = "mod3"
SUPER = "mod4"
CTRL = "control"
SHIFT = "shift"
SPACE = "space"
BACKSPACE = "BackSpace"
RETURN = "Return"
DELETE = "Delete"
TAB = "Tab"

EXCLAM = "exclam"
QUOTEDBL = "quotedbl"

PRINT = "Print"
HOME = "Home"
END = "End"

LEFT = "Left"
RIGHT = "Right"
UP = "Up"
DOWN = "Down"

AUDIO_RAISE_VOLUME = "XF86AudioRaiseVolume"
AUDIO_LOWER_VOLUME = "XF86AudioLowerVolume"
AUDIO_MUTE = "XF86AudioMute"
AUDIO_NEXT = "XF86AudioNext"
AUDIO_PREV = "XF86AudioPrev"
AUDIO_PLAY = "XF86AudioPlay"
AUDIO_STOP = "XF86AudioStop"

BRIGHTNESS_UP = "XF86MonBrightnessUp"
BRIGHTNESS_DOWN = "XF86MonBrightnessDown"
