name: Validate workflows
permissions:
  contents: read
on:
  push:
    paths:
      - .github/zizmor.yml
      - .github/actionlint-matcher.json
      - .github/workflows/**
      - .github/actions/**
  pull_request:
    paths:
      - .github/zizmor.yml
      - .github/actionlint-matcher.json
      - .github/workflows/**
      - .github/actions/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # necessary for zizmor checks
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Run zizmor
        run: uvx zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          ./actionlint -color
